services:


  # web service, frontend and backend included
  web:
    build: .  # build the docker, using the dockfile in current dir

    command: ["sh", "-c", "python manage.py migrate && python manage.py runsslserver 0.0.0.0:8000 --certificate certs/cert.crt --key certs/private.key"]

    ports:
      - "8000:8000"

    volumes:
      - .:/usr/src/app  # mount the project dir to the docker

    environment:
      - DJANGO_DEV_SERVER_PORT=8000
