"""
Django settings for eventcalendar project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import base64
from datetime import timedelta
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "i8e1s3!_(fjsiv%1pn3sb3o=s)!p*nzwh1$gp5-l&%nb!d=y_s"

PUBLIC_KEY_N = 17703830693294865218947795164640051138835199390747672312611477756520237948974923066840429252234480580577436693941565095096573125178129280813161223382969636519209241377541829442660999922361157975263933427197337973898335716894004821821779955516895115396427119798820952118409777804029431888454328008642668743930915223051741504006448084968772372660334221673080395427595285721728172392313421806501314378258027661313877170358875965738935597080584219191386610173897441219702421784874380498778660619199607568767901906784603867943125460620456877187497398239070846601408834058257861190211842924400113629424486749257480321983139
PUBLIC_KEY_E = 65537
PRIVATE_KEY_N = 17703830693294865218947795164640051138835199390747672312611477756520237948974923066840429252234480580577436693941565095096573125178129280813161223382969636519209241377541829442660999922361157975263933427197337973898335716894004821821779955516895115396427119798820952118409777804029431888454328008642668743930915223051741504006448084968772372660334221673080395427595285721728172392313421806501314378258027661313877170358875965738935597080584219191386610173897441219702421784874380498778660619199607568767901906784603867943125460620456877187497398239070846601408834058257861190211842924400113629424486749257480321983139
PRIVATE_KEY_E = 65537
PRIVATE_KEY_D = 9090849662350307447903476672347401330168011430136127932867144680717389683642111875251857204715610647087484582162984118059797906245625901203981180867404323935806469629040315947233938544443902670881443331636663485292288201788820731323807327814975835305796143592012473894759361161466079792210141235996202111003736392134010031536174056628613099710153043400642659945399728392125393423055869596870015890954621362146065452449167995823276401397015204893640022807080015248147978229776633503680390933600589766506367344102026026486886005448165641672129070975801014265184377562338455749964888741565704018744497854766420624016337
PRIVATE_KEY_P = 2302151111895922819814520847283790376563737509145687722363973150337580494856731695874577454825129121171618219625288042722598833646781761376242518674575545382342386322313195390643675731870097329646343489744205765027111402795639673340146459168935194440462650501507995608839152029428110337375286890034317259355382243235889599792937
PRIVATE_KEY_Q = 7690125379612887802358428310877071577231123446026258119067779078537823699954422294761189439603700031130795151731626202159661562706494683013102299256586680536893820526573719245268659564559841413930532100901183585999389090753619366937834873955731464210017138695527916247508930357403029082347

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False
DEFAULT_AUTO_FIELD='django.db.models.AutoField' 

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "calendarapp.apps.CalendarappConfig",
    "accounts.apps.AccountsConfig",
    "axes",
    'encrypted_model_fields',
    'honeypot'
]

# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'CONNECTION_POOL_KWARGS': {
#                 'max_connections': 100,
#                 'retry_on_timeout': True,
#             }
#         }
#     }
# }

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend'
]


ROOT_URLCONF = "eventcalendar.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "eventcalendar.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'calendar_db',                      
#         'USER': 'user',
#         'PASSWORD': '!!UZH_CNSP24_CALENDAR!!',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


"""
##CONECTAR CON POSTGRES
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'proyectoHadaMadrina',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '127.0.0.1',
        'DATABASE_PORT': '5432',
        
    }
}

"""

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation." "MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation." "CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation." "NumericPasswordValidator"},
]

AUTH_USER_MODEL = "accounts.User"

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = False

AXES_FAILURE_LIMIT = 10  # Number of failed attempts

AXES_COOLOFF_TIME = timedelta(minutes=5)  # Lockout period after reaching failure limit

SECURE_SSL_REDIRECT = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
"""
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
"""


STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
#STATIC_ROOT=os.path.join(BASE_DIR, 'static/')

#
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/') # 'data' is my media folder
MEDIA_URL = '/media/'